version: '3'
services:
  kotoba-bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    restart: always
    environment: 
      MONGO_HOST: 'mongo_readwrite:27017'
      WORKER_HOST: 'kotoba-worker'
    volumes:
      - ./user_data/bot:/var/app/data
      - ./user_data/shared_data:/var/shared_data
    depends_on:
      - mongo_readwrite
  kotoba-web:
    build:
      context: .
      dockerfile: ./kotobaweb/Dockerfile
    restart: always
  kotoba-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    environment: 
      MONGO_HOST: 'mongo_readwrite:27017'
    volumes:
      - ./user_data/shared_data:/var/shared_data
    depends_on:
      - mongo_readwrite
  kotoba-worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: always
    environment: 
      MONGO_HOST: 'mongo_readwrite:27017'
    depends_on:
      - mongo_readwrite
  mongo_readwrite:
    image: mongo:4.0.9
    restart: always
    volumes:
      - ./user_data/mongo_readwrite_data:/data/db
  nginx:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
