version: '3'
services:
  kotoba:
    image: mistval/kotoba
    build: .
    restart: always
    volumes:
      - ./data:/var/app/data
      - ./latest_log:/var/app/latest_log
      - ./config:/var/app/config
