version: '3'
services:
  kotoba-bot:
    image: registry.gitlab.com/kotoba/monochrome2/bot:latest
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    restart: always
    environment: 
      MONGO_HOST: 'mongo_readwrite:27017'
      WORKER_HOST: 'kotoba-worker'
      FORCE_COLOR: '1'
    volumes:
      - ./user_data/bot:/var/app/data
      - ./user_data/shared_data:/var/shared_data
      - ./config:/var/config
    depends_on:
      - mongo_readwrite
  kotoba-web:
    image: registry.gitlab.com/kotoba/monochrome2/web:latest
    build:
      context: .
      dockerfile: ./kotobaweb/Dockerfile
    restart: always
  kotoba-api:
    image: registry.gitlab.com/kotoba/monochrome2/api:latest
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    environment: 
      MONGO_HOST: 'mongo_readwrite:27017'
    volumes:
      - ./user_data/shared_data:/var/shared_data
      - ./config:/var/config
    depends_on:
      - mongo_readwrite
  kotoba-worker:
    image: registry.gitlab.com/kotoba/monochrome2/worker:latest
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: always
    environment: 
      MONGO_HOST: 'mongo_readwrite:27017'
    depends_on:
      - mongo_readwrite
  mongo_readwrite:
    image: mongo:4.0.9
    restart: always
  nginx:
    image: registry.gitlab.com/kotoba/monochrome2/nginx:latest
    build: ./nginx
    restart: always
    ports:
      - '80:80'
